### PR TITLE
minor: change line ends to linux by IDEA

### PR DESCRIPTION
**Pull request by romani**
just noticed in IDEA

### CODE REVIEW

**Comment by rnveach** [comment]
Why isn't CI catching this? Don't we run checkstyle with newline end?

**Comment by rnveach** [comment]
I confirmed on my local linux that the `\r\n` is there on the end.

````
/home/ricky/opensource/contribution/releasenotes-builder$ xxd src/test/java/com/github/checkstyle/MainTest.java

....
000023c0: 2020 2020 7d0d 0a20 2020 207d 0d0a 7d0d      }..    }..}.
000023d0: 0a        
````

**Comment by romani** [comment]
It is gap in checkstyle on this
https://stackoverflow.com/a/41632241/1015848
https://github.com/checkstyle/checkstyle/issues/893#issuecomment-113293027

**Review by rnveach — CHANGES_REQUESTED** [review]
If this is something we can't fix, then you will need to recheck all the work I do and push in all the repos. I changed more than this 1 file in my test update PR. I also added those Util classes.

**Comment by rnveach** [comment]
My commits with new files.
e5271cf2127f704962054525eab4ace55f921136
654a97ee7883f0e46cce0ff11bfb8a6958e3c970
13fad27fe57997325b1a8cedaff6ab31859b9859

Once my swarm of PRs are merged, I can see if I can identify all files, otherwise only linux users will be able to tell.

**Comment by rnveach** [comment]
@romani Please review my swarms and merge, and I can take over fixing this.

**Comment by rnveach** [comment]
Closing this in favor of https://github.com/checkstyle/contribution/pull/719

**Pull request closed without merging**
