### PR TITLE
minor: exclude non-compilable files in openjdk17

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Added noncompilable file to the exclusion list.
Found at https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/514d736_2022085653/reports/diff/openjdk17/index.html#A3

Report with exclusion (Free from NPE 99.99%): https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/25afbb6_2022171118/reports/diff/index.html

### CODE REVIEW

**Comment by nick-mancuso** [comment]
Please generate diff report in https://github.com/checkstyle/checkstyle/pull/11468 using raw text link to this file to show that exclusion works, and share new report here.

**Comment by Vyom-Yadav** [comment]
> Please generate diff report in https://github.com/checkstyle/checkstyle/pull/11468 using raw text link to this file to show that exclusion works, and share new report here.

Shared in PR description

**Comment by Vyom-Yadav** [comment]
Here is the raw link: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/803f37746222b8c340df985e393405447cea7c23/projects-to-test-on.properties

**Review by nick-mancuso — APPROVED** [review]

**Review by rnveach — APPROVED** [review]
Can't tell anything without https://github.com/checkstyle/contribution/issues/588

**Pull request merged**
