### PR TITLE
Pull #784: Add script for separating modules in pages

### PR DESCRIPTION
**Pull request by stoyanK7**
Adds script for separating modules into pages and an explanation on how to run it.

### CODE REVIEW

**Comment by stoyanK7** [comment]
Huh, didn't know that markdownlint expects ordered lists to be 
```
1.
1.
1.
..
```
by default.
https://app.circleci.com/pipelines/github/checkstyle/contribution/111/workflows/bfa4b635-e50c-4dc7-aa4c-6a3c88727e6b/jobs/752?invite=true#step-102-162
https://github.com/DavidAnson/markdownlint/issues/45#issuecomment-277859620

Do I just change to that?

**Comment by nrmancuso** [comment]
This is a weird default, IMO. Please update the config to use `ordered`: https://github.com/DavidAnson/markdownlint/issues/45

**Comment by stoyanK7** [comment]
Done.

**Comment by romani** [comment]
No rush to merge this script, it supposed to be used few times only.

**Comment by romani** [comment]
Did you decided to not merge or upset that we are not merging it?

**Comment by stoyanK7** [comment]
Oh no, I just understood that we are not merging it so I closed the PR.

**Comment by nrmancuso** [comment]
@stoyanK7 please leave PR open, push changes as we need to, and we will merge at end of summer

**Comment by romani** [comment]
We will decide at end of project.
Code of PR staying forever even after fork is removed. So we can skip merge, and will still be with us if required by search of closed PR.

**Comment by romani** [comment]
@stoyanK7 , do you still need this PR ?

**Comment by stoyanK7** [comment]
Not really. Feel free to close it. Separation is done.

**Comment by romani** [comment]
any code that is referenced in PR will stay availble forever even after fork removal

**Pull request closed without merging**
