### PR TITLE
Issue #461: Add information about added/removed violations on main report page

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Fixes Issue #461 
Diff Report: [here](https://abhishek-kumar09.github.io/IndentaionReport/reports2/diff/index.html) 
Screenshot until site is resolved:
Screenshot from 2020-05-24 11-57-52

### CODE REVIEW

**Comment by rnveach** [comment]
@Abhishek-kumar09 Please see romani's comment on creating a report with a lot of projects and violations so we can get a handle of what it will look like.

**Comment by Abhishek-kumar09** [comment]
OK @rnveach , I am doing so.

**Comment by romani** [comment]
Looks good, but a bit more text .. @strkkk , @rnveach , @pbludov is it better to do:
image

**Comment by Abhishek-kumar09** [comment]
I don't know if it is a good idea to introduce some elaborating colors, but you can have a look:
Screenshot_2020-05-26 Checkstyle Tester Report Diff Summary(1)

**Comment by strkkk** [comment]
@romani I like the latest screenshot from @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
[Latest Diff Report](https://abhishek-kumar09.github.io/IndentaionReport/reports/diff/index.html) after applying changes.

**Comment by romani** [comment]
I like colored page too.

**Comment by romani** [comment]
@strkkk , you are author of issue, please review PR and approve it.

**Pull request merged**
