### PR TITLE
Issue #364: releasenotes-builder: avoid extra line wrapping

### LINKED ISSUE #364: releasenotes-builder: avoid extra line wrapping
https://github.com/checkstyle/contribution/issues/312#issuecomment-478472949

It is better to not wrap line if it could fit in line limit 100 symbols per line. Xdoc file has certain indentation that unlikely to change.

Additional minor issue is to trim spaces in front of issue title, it is visible in non xdoc content.

### PR DESCRIPTION
**Pull request by stoyanK7**
Resolves #364

### CODE REVIEW

**Comment by stoyanK7** [comment]
This issue's requirements feel like they are scattered all around. So should we add a test case for 100-character title or just 87-character title (+13 indentation whitespace characters that are added)?

Moreover, it appears adding a 100 character test case like this one
```java
            createReleaseNotesMessage("Mock issue title 7 thisReleaseNoteShouldBeExactly100Charact"
                + "ersLongSoWeTestMaxLineLimit123456789ooooo", "Author 1"));
```
is not being split up correctly and results in this `114` char long row.
```
          <li>
            Mock issue title 7 thisReleaseNoteShouldBeExactly100CharactersLongSoWeTestMaxLineLimit123456789ooooo.
            Author: Author 1
          </li>
```

**Comment by romani** [comment]
>So should we add a test case for 100-character title or just 87-character title (+13 indentation whitespace characters that are added)?

Both, we just need to wrap by spaces.

**Comment by romani** [comment]
>is not being split up correctly

Yes, we need to split only by space

**Review by romani — APPROVED** [review]
ok lets, see how it works on real releasenotes

**Comment by stoyanK7** [comment]
Seems fine on local, but I do not see a PR with such long message(100+ chars).

**Pull request merged**
