### PR TITLE
target directory was dropped twice: via rm and mvn clean

### PR DESCRIPTION
**Pull request by damianszczepanik**

### CODE REVIEW

**Comment by damianszczepanik** [comment]
Using native rm on Windows caused problem when path extended NTFS path limit. Maven does not have this problem and successfully remove and recreate `target` directory

**Comment by romani** [comment]
I do not see "mvn clean" in  your changes

**Comment by damianszczepanik** [comment]
Because it was already there.

**Comment by romani** [comment]
https://github.com/damianszczepanik/contribution/blob/df17fed7353bedb5935c8648f900ede1867b2a88/checkstyle-tester/launch.sh#L29 , ok , sorry, misunderstand your comment.

**Pull request merged**
