### PR TITLE
Issue #4557: fix NPE

### PR DESCRIPTION
**Pull request by sergileon**
fixed NPE for [https://github.com/checkstyle/checkstyle/pull/5026](https://github.com/checkstyle/checkstyle/pull/5026)

### CODE REVIEW

**Comment by Vladlis** [comment]
Lets wait for results of https://github.com/checkstyle/checkstyle/issues/4557#issuecomment-326503937

**Comment by Vladlis** [comment]
@romani 
Seems like NPE from Wercker does not reproduce on local - this might be Wercker problem?
Can merge this PR and see whether the problem repeats?

**Comment by romani** [comment]
I do not see wercker problem at all, lets see problem first.

**Comment by romani** [comment]
@sergileon , please next time be attentive what issue to reference in commit message.
This report have separate issue tracker.

**Pull request merged**
