### PR TITLE
Issue #250: update versions of some projects

### PR DESCRIPTION
**Pull request by nick-mancuso**
Also fixes failure noted at https://github.com/checkstyle/checkstyle/issues/11685

### CODE REVIEW

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
@nick-mancuso I assume this is draft to determine if spoon will complete with just this?

**Comment by nick-mancuso** [comment]
@rnveach @romani we can merge this to fix broken master build in main project, I have created https://github.com/checkstyle/contribution/issues/610 so that we can come back to better exclusion list for spoon.

**Comment by nick-mancuso** [comment]
Proof that this change fixes master build is at https://circleci.com/gh/checkstyle/checkstyle/140905?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by romani** [comment]
Let's merge this, if they do not enforce compilation, It it's safer to keep all off

**Pull request merged**
