### PR TITLE
Test enabling launch.sh

### PR DESCRIPTION
**Pull request by rnveach**
Test. Don't merge.

### CODE REVIEW

**Comment by rnveach** [comment]
Issue still exists. I can't reproduce locally.

**Comment by rnveach** [comment]
> mbox note: This setup is version 2.877, but setup.ini claims version 2.879 is available.
You might want to upgrade to get the latest features and bug fixes.

**Comment by rnveach** [comment]
https://ci.appveyor.com/project/Checkstyle/contribution/build/465#L73
Seems the only thing that works is checking the line's length.

**Comment by romani** [comment]
@rnveach , is this PR is still actual ?

**Comment by romani** [comment]
@rnveach , ping

**Comment by rnveach** [comment]
I will just close this for now.

**Pull request closed without merging**
