### PR TITLE
Tool for release notes section generation for releasenotes.xml file

### PR DESCRIPTION
**Pull request by MEZk**
@romani 

**Command line args:**
[0] - release number. For example, 6.13.
[1] - path to local git repository. For example, /media/andreiselkin/TOURO/IDEA_Projects/checkstyle
[2] - start commit reference. For example,  753bc06  or just tag  'checkstyle-6.12.1'
[3] - (optional) end commit reference. HEAD reference will be used if not specified.

**Note**, I use anonymous connection to GitHub to grab issues and you can be banned by GitHub if you use release notes generation too many times. 

I'll generate jar after your code review.

### CODE REVIEW

**Comment by MEZk** [comment]
@romani 
Should I collect all [ERROR] messages, print all of them and fail the build?
https://github.com/MEZk/contribution/commit/ce03562f1b5cb4c87176b630ccc94297e00f6b06#diff-9c47c22374718bd0b5879fc98c3646a2R280

**Comment by romani** [comment]
> Should I collect all [ERROR] messages, print all of them and fail the notes generation?

can you give me example of output with ERRORs

**Comment by romani** [comment]
please add README.txt file to describe how to run/use it. There should be example of commands to compile and run from terminal.

**Comment by MEZk** [comment]
@romani 

````
[WARN] Issue #2451 is not closed!
[WARN] Issue #957 is not closed!
[WARN] Issue #2541 is not closed!
[WARN] Issue #2540 is not closed!
[WARN] Issue #2557 is not closed!
[ERROR] Issue #2451 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2589 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2581 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2516 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #957 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2067 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2541 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2540 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #1438 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2344 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2557 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2161 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #1031 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #1930 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
[ERROR] Issue #2290 does not have 'new feature', 'breaking compatibility', 'miscellaneous', or 'bug' label.
````

**Comment by MEZk** [comment]
@romani 
>please add README.txt file to describe how to run/use it. There should be example of commands to compile and run from terminal.

Done.

**Comment by romani** [comment]
@MEZk ,

1)
> package io.github.mezk;

com.github.checkstyle

2)
>        final String startRef = args[2];
        final String endRef = getEndReference(args);

Looks strange why endRef require whole "args". Please inline getEndReference to "main()"

3)
> formReleaseNotes

" form" --> build or make . Please apply this to all other methods.

4)
>         final String releaseNo = args[0];
        final String localRepo = args[1];
        final String startRef = args[2];

order of arguments should be "source -> target" "where -> what". So: repoPath, startRef, endRef, ReleaseName

5)
>         if (!validArgs) {
            System.exit(1);

the same as for method - One exit point from Application ! 

6)
>    private static void checkCommandLineArgs(String[] args) {
        boolean validArgs = true;
        if (args.length == 0) {
            System.err.println("You must specify command line arguments.");

if method is do validation let him do only this, and "main()" method will print messages to required location (in your case it is System.err)

7)
>                 final GitHub github = GitHub.connectAnonymously();
               final GHRepository repo = github.getRepository(REMOTE_GIT_REPO_PATH);

move this lines above while, as you need to create this ones, and reuse.

8)
> getIssueNumberFromCommitMessage(commitMessage);

getIssueNumber(commitMessage);  - "(" is read as "from", commitMessage is already written.
Please apply this to all other methods.

9)
> commitsForRelease.removeAll(issueCommits);

changing  collections that you iterate is not good approach and very error prone. Please iterate over collection by foreach and skip processing by some find function.

10)
>                 releaseNotes.put(MISCELLANEOUS_LABEL, releaseNotesMessage);
                commitsForRelease.remove(commit);

please move this out of IF to have it ones. IF should calculate values or these lines.

11)
 >  final int octothorpIndex = commitMessage.indexOf('#');

http://blog.codinghorror.com/ascii-pronunciation-rules-for-programmers/ search for "#" names.

12)
> for (int j = 0; j < commits.size(); j++) {

why not foreach ? the are few cases like this.

13)
>             for (int j = 0; j < commitAuthors.size() - 1; j++) {
                sb.append(commitAuthors.get(j));
                sb.append(", ");
            }

http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Joiner.html#appendTo%28java.lang.StringBuilder,%20java.lang.Iterable%29


14)
>  final String releaseNotesMessage = String.format(
            "        <li>\n          %s. %s %s\n        </li>",

Manual HTML composition is nightmare for future support ..... , NOT a solution is 21 century. Please use http://www.thymeleaf.org/ , try to use " Thymeleaf 3.0.0" even it is a beta, your template is so simple, so it should be ok.

**Comment by MEZk** [comment]
@romani 
1) Done.
2) Done.
3) Done.
4) Done.
5, 6) Used Preconditions from Guava instead.
7) Done.
8) Done.
9) Done.
10) Done.
11) Done. Thanks for info.
12) Done.
13) Done.
14) I used FreeMarker instead. I was familiar with it but had forgotten to use it.

**Comment by romani** [comment]
README.md

1)please review how your README looks like on github, too much weird formatting and extra symbols.
Typos, non existing package. Please provide real example of command.

2)
> []

what is it ?

------------

NotesBuilder.java 

1)
> private static List<String> errors = new ArrayList<>();
    private static List<String> warnings = new ArrayList<>();

please wrap these to class ,and add there also releasenotes

2)
> System.exit(1);

single point of exit !!!!

3)
> generateReleaseNotesXmlFile

Why XML ?  it will do what I defined in template.

4)
> System.out.println("\n[INFO] Generation success!");
        System.out.println("[INFO] See " + OUTPUT_FILE);

combine to one line. Make it "generation succeed!".

5)
> Generation fail!

Generation failed!

6) 
>  if (commitMessage.startsWith("Issue") || commitMessage.startsWith("Pull")) {
if (commitMessage.contains("Issue") || commitMessage.contains("Pull")) {

Does it mean the same ?

7)
> buildReleaseNotesMessageForIssue
buildReleaseNotesMessageForCommit
getSectionNameFor

What is obsession with "For" ?

8)
> String.format("[ERROR] Issue #%d does not have '%s', '%s', '%s', "
                    + "or '%s' label.", issueNo, NEW_LABEL, BREAKING_COMPATIBILITY_LABEL,
                    MISCELLANEOUS_LABEL, BUG_LABEL);
BREAKING_COMPATIBILITY_LABEL.equals(labelName)
            || NEW_LABEL.equals(labelName)
            || BUG_LABEL.equals(labelName)
            || MISCELLANEOUS_LABEL.equals(labelName);


Please make an sorted array from these values.

9)
>buildReleaseNotesMessageForIssue

I do not think this deserve to be method.

10)
> final String author = "Author: " + currentCommit.getAuthorIdent().getName();

Why this constant is not a part of Template ?

11)
I do not see that order of groups will be defined as we have in our web site, please make it possible to make each group be defined in template.

**Comment by romani** [comment]
> releasenotes.ftl

Can you argument why FreeMarker is better in this case? 
In My mind naturally looking templates are better in simple cases (performance is not an issue in our case) - http://www.thymeleaf.org/doc/articles/thvsjsp.html, http://www.thymeleaf.org/doc/articles/layouts.html#thymeleaf-standard-layout-system (template is could be opened in browser in the same way as generation result).

**Comment by romani** [comment]
support of reverts 

this rare case but is there a simple way to support reverts ? Example: https://github.com/checkstyle/checkstyle/issues/2616#issuecomment-157719561 . We could reply on "Revert \"" in commit mesage.

**Comment by MEZk** [comment]
@romani 
README.md
1) Done.
2) Done.

NotesBuilder.java
1) Done.
2) Done.
3) Renamed.
4) Done.
5) Done.
6) Extracted to the 'isIssueOrPull' method.
7) Corrected.
8) Done.
9) Why? I overloaded the method 'buildReleaseNotesMessage'.
10) Done. Hardoded 'Author' in template.
11) Done.

Additions:
1) Added template for thymeleaf with sections.
2) Corrected template for freemarker. Added sections.

For now I am working on revert commits.

**Comment by MEZk** [comment]
@romani 
>support of reverts 
1) What should we do with revert commits themselves? Should we add them into release notes?
2) What should we do if revert commit reverts the commit from previous release?

**Comment by romani** [comment]
> 1) What should we do with revert commits themselves? Should we add them into release notes? In what section? Format?

if we do revert of commit, initial changes and this revert should not be appeared in release notes.

> What should we do if revert commit reverts the commit from previous release?

All changes between releases are functional changes that HAVE to be mentioned.

> If not, add revert commit into release notes, but again in what format, section?

in a section that is defined by message and issue referenced in it.

**Comment by romani** [comment]
thymeleaf_template.html

1)
>  Added template for thymeleaf with sections.

Template looks not clear as lines are so long, this might help - http://stackoverflow.com/a/29317466/1015848 , please try to keep some example text in template.

You have both templates, what engine you like more ?

2)
> breakingBackwardCompatibilityMessages

name "breakingMessages" should be enough.

------------------------------

README.md

3)
> Jar file which includes all required dependencies will be put into

"Jar file which includes all required dependencies will be located at /releasenotes-xdoc-builder/target/releasenotes-xdoc-builder-1.0-all.jar"

4)
> java -jar releasenotes-xdoc-builder-1.0-all.jar /media/andreiselkin/TOURO/IDEA_Projects/checkstyle/ checkstyle-6.12.1 6.13

is it real command, I do not see startRef

-----------------

pom.xml

5)
Code have too long lines, checkstyle enforcement is missed :) .

Please enforce our checkstyle_config.xml over this code, throught maven-checkstyle-plugin in build phase, usage of latest release version (RELEASE) is ok.

-----------------------------------

ReleaseNotesMessage.java

6) Class should be final as you override equals and hashcode. 

7) did you generate equals and hashcode by IDE ? I do not see usage of issueNumber field. 
Do we really need to override equals and hashcode ?

------------------------------

NotesBuilder.java

8)
>        final String endRef = args.length == 4 ? args[2] : "HEAD";
        final String releaseNo = args.length == 3 ? args[2] : args[3];

I do not like this magic with indexes, can we use named parameters in CLI ?

9)
> if ("".equals(issueLabel)) {

issueLabel.isEmpty() ?

10) 
>  result.putReleaseNotesMessage(issueLabel, releaseNotesMessage);

I know I asked you to make this line to be below IF.
This line still looks weird as "result" is updated above in IF, it is better to keep "result." close to each other. Please move it back to IF blocks.

11)
> ```private static List<String> findCommitAuthors(```

it could be a Set.

12)
>```         final Collection<GHLabel> issueLabels =  issue.getLabels();
        final Iterator<GHLabel> ite = issueLabels.iterator();
        while (ite.hasNext()) {
```

this is just a search in collection, can we use Guava's implementation.

13)
> private static ReleaseNotesMessage buildReleaseNotesMessage(GHIssue issue, String authors)
private static ReleaseNotesMessage buildReleaseNotesMessage(RevCommit currentCommit)

By additional method you create additional level of abstraction, that human need to keep in mind. It is good for methods with logic. You do not use this methods a lot (only in 2 places). You can easily inline them, and inline "issue.getTitle();" directly to c-tor.

**Comment by MEZk** [comment]
@romani 

**thymeleaf_template.html**
1) Done. Freemarker is easier and has more clearer syntax. I dont like thymeleaf at all. I have found a few bugs in thymeleaf. Should be discussed in Skype.
2) Done.

**README.md**
3) Done.
4) startRef = checkstyle-6.12.1. You can use both sha-1 or tag.

**pom.xml**
5) Done partially. ImportOrder, Header, UncommentedMain, ImportControl have been excluded from checkstyle_checks.xml configuration.
There are a few violations left. What should I do?

```
[ERROR] src/main/java/com/github/checkstyle/NotesBuilder.java:[50,1] (metrics) ClassDataAbstractionCoupling: Class Data Abstraction Coupling is 11 (max allowed is 7) classes [ClassLoaderTemplateResolver, Configuration, Context, File, FileRepositoryBuilder, FileWriter, Git, Predicate, ReleaseNotesMessage, Result, TemplateEngine].
[ERROR] src/main/java/com/github/checkstyle/NotesBuilder.java:[50,1] (metrics) ClassFanOutComplexity: Class Fan-Out Complexity is 27 (max allowed is 25).
[ERROR] src/main/java/com/github/checkstyle/NotesBuilder.java:[127,44] (design) ThrowsCount: Throws count is 3 (max allowed is 2).
```

How can we remove inline conditionals and do not affect the length of the methods? 

```
[ERROR] src/main/java/com/github/checkstyle/NotesBuilder.java:[132,41] (coding) AvoidInlineConditionals: Avoid inline conditionals.
[ERROR] src/main/java/com/github/checkstyle/NotesBuilder.java:[134,42] (coding) AvoidInlineConditionals: Avoid inline conditionals.
[ERROR] src/main/java/com/github/checkstyle/NotesBuilder.java:[360,30] (coding) AvoidInlineConditionals: Avoid inline conditionals.
```

**ReleaseNotesMessage.java**
6, 7) We don't nead to override hashcode and equals. Both meathods have been removed.

**NotesBuilder.java**
8) Done.
9) Done.
10) Done.
11) Done.
12) Done. See [getIssueLabelFrom](https://github.com/MEZk/contribution/commit/f828937c9c2bf5dbd304973bf592529327421e0d#diff-95c961da935625fe120975931b896e37R352). I don't like this approach with predicate. Did I use it correctly?
13) Done.

**Comment by MEZk** [comment]
@romani 

Please fix the following ERRORS to let me control the whole context of output file and do not comment out https://github.com/MEZk/contribution/commit/f828937c9c2bf5dbd304973bf592529327421e0d#diff-95c961da935625fe120975931b896e37R140

[WARN] Issue #2530 is not closed!
[WARN] Issue #2451 is not closed!
[WARN] Issue #2590 is not closed!
[WARN] Issue #957 is not closed!
[WARN] Issue #2541 is not closed!
[WARN] Issue #2540 is not closed!
[WARN] Issue #2557 is not closed!

[ERROR] Issue #2530 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2451 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2607 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2605 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2590 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2586 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2585 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #957 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2067 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2541 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2540 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2557 does not have breaking compatibility, bug, miscellaneous, new feature label!

**Comment by romani** [comment]
> Please fix the following ERRORS to

fixed

**Comment by romani** [comment]
1)
> java -jar releasenotes-xdoc-builder-1.0-all.jar /media/andreiselkin/TOURO/IDEA_Projects/checkstyle/ checkstyle-6.12.1 6.13

please make it:
java -jar releasenotes-xdoc-builder-1.0-all.jar -localGitPath /media/andreiselkin/TOURO/IDEA_Projects/checkstyle/ -startRef checkstyle-6.12.1 -releaseNumber 6.13

see example: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L156

2)
> checkstyle_checks.xml

remove it and use it by http. see example - https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/pom.xml#L81

3)
> There are a few violations left. What should I do?

ClassFanOutComplexity, ClassDataAbstractionCoupling - as we already have 3 classes for this project, please do further decomposition on subclasses.
ThrowsCount - suppress it for main() method.

4)
> ```<cacheFile>${project.build.directory}/checkstyle/checkstyle-cachefile<```

you do not need cache file - remove it.

5)
> args.length == FOUR_ARG_CMD ? args[END_REF_OR_RELEASE_INDEX] : HEAD_REF;

see point "1)"

6)
> System.out.println("\n[INFO] Generation succeed!\n[INFO] See " + OUTPUT_FILE);

remove "\n[INFO]".

7)
> connectUsingPassword("MEZk", "xxxxxx"); 

please remove. If you still want to use it, do it through CLI argument

8)
> 
            final String issueLabel;
            final ReleaseNotesMessage releaseNotesMessage;

move inside child blocks.

9)
> public boolean apply(GHLabel input) {

move method of anonymous class to right +4 indentation.

10)
> thymeleaf_template.html

wrap long line to be multi-line. "\n" before " th:href" should be ok. We could make some changes to original format to make lines more short. I do not happy with long lines. 100-120 symbols is enough.

**Comment by MEZk** [comment]
@romani 
Issue title should be corrected

```Checkstyle throw NumberFormatException on Japanese locale then sizes and metrics Checksa are used..  ``` <a href="https://github.com/checkstyle/checkstyle/issues/2601">#2601</a>

**Comment by romani** [comment]
title is fixed.

**Comment by MEZk** [comment]
@romani 
Should I suppress Header and RegexpHeader ?

**Comment by romani** [comment]
1) please fix if possible to use template by url, if not, open issue on this and suppress.
2) suppress
3) any way, annotation is better in this case.

**Comment by MEZk** [comment]
1) Done.
2) Done.
3) Done.
4) Done.
5) Done.
6) Done.
7) I exceeded limit of connections and Github banned me. So, I used private connection and forgot to change it to anonymous before commit. 
8) Done. 
9) Can not do this. IndentationCheck rises a violation.
10.1) I can not wrap lines which contain 'block' tags because if the condition inside 'block' is false, thymeleaf will insert 3 empty lines instead the block.
10.2)

 > "\n" before " th:href" should be ok.

Done.

>1) please fix if possible to use template by url, if not, open issue on this against main project and suppress.

Used header template by url. See checkstyle.properties.

**Comment by romani** [comment]
freemarker.template

1)
please add "\n" before ```<a>``` to keep lines short, about 100 symbols, it is even problem to review a code at github.

------

thymeleaf_template.html

2)
> ```<th:block th:if...```

I kind of see a reason why you hide TH tags, but this is not fare in our comparison between formatters and look very unusual. Please format according to indentation levels.

-----------

3)
What force you to make all classes package-private  and final ? it is ok, but ....

------------

TemplateProcessor

4)
> THYMELEAF_TEMPLATE_FILE = "thymeleaf_template"
...
templateResolver.setSuffix(".html");

can we avoid usage of `setSuffix` ? and keep name is usual form.

--------------

NotesBuilder

5)
> final Result result = buildResult(localRepo, startRef, endRef); 
....

please move this functional block of code out of main(), to clearly show border of CLI and logic.

6)
Please ad System.exit(some error code) to the end of main(). If smth wrong happen - you have to exit with non 0 error code. This will help to use your CLI in shell scripts.

7)
>        final GitHub github = GitHub.connectAnonymously();
        final GHRepository repo = github.getRepository(REMOTE_REPO_PATH);

Now I know that you send me a code that you actually does not run :), never to this, it is fragile model, if you need special authorization for debug - do add it as a mode.
As I mention before , please add auth by token as option of CLI (anonymous is default).

8)
Please share and example(full html page `mvn clean site -Dlinkcheck.skip=true`) of release notes generation that will be for 1.13 release. Result of generation should by just copy-pasted to xdoc without any changes.

**Comment by MEZk** [comment]
@romani 
Some typos in issue titles
create HTML web page to describe how to open issues agains**t** Checkstyle. <a href="https://github.com/checkstyle/checkstyle/issues/2344">#2344</a>

ParameterName: new option to skip methods **with** Override annotation. <a href="https://github.com/checkstyle/checkstyle/issues/2290">#2290</a>

Checkstyle throws NumberFormatException on Japanese locale **when** sizes and metrics Checks are used. <a href="https://github.com/checkstyle/checkstyle/issues/2601">#2601</a>

FallThroughCheck handle**s** finally incorrectly.  <a href="https://github.com/checkstyle/checkstyle/issues/1438">#1438</a>

**Comment by romani** [comment]
fixed.

**Comment by MEZk** [comment]
@romani 

```
[WARN] Issue #2080 is not closed!
[WARN] Issue #2451 is not closed!
[WARN] Issue #2590 is not closed!
[WARN] Issue #957 is not closed!
[WARN] Issue #2541 is not closed!
[WARN] Issue #2540 is not closed!
[WARN] Issue #2557 is not closed!

[ERROR] Issue #2080 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2526 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2519 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2480 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2436 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2495 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2517 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2346 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #1627 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2513 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2292 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #1267 does not have breaking compatibility, bug, miscellaneous, new feature label!
[ERROR] Issue #2122 does not have breaking compatibility, bug, miscellaneous, new feature label!
```

**Comment by romani** [comment]
long running tasks: 2080 , 2451, 957, 2541, 2540, 2557

closed: 2590

**Comment by MEZk** [comment]
@romani 

[ERROR] Issue #2480 does not have breaking compatibility, bug, miscellaneous, new feature label!

**Comment by MEZk** [comment]
1) Can not do this. If I add "\n" before <a>, a release notes message will be formatted like the following:

Release notes message. Author : author
<a href="http://reference">#2222</a>

2) Done.
3) Made them public and non-final except Constants.
4) Removed usage of suffix.
5) Done.
6) Done.
7) Done.

Are CliOptions and ReleaseNotesMessage good candidates for Builder pattern?
http://jlordiales.me/2012/12/13/the-builder-pattern-in-practice/

**Comment by romani** [comment]
> Are CliOptions and ReleaseNotesMessage good candidates for Builder pattern ?

CliOptions - make sense to update.
ReleaseNotesMessage - no reason to update, it has very small c-tor.

**Pull request merged**
