### PR TITLE
config: Extend project list with two new projects that uses java21 code

### PR DESCRIPTION
**Pull request by mahfouz72**

### CODE REVIEW

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Please do:
 - lowercase commit prefix
 - test this using GitHub action in main repo

**Comment by romani** [comment]
@relentless-pursuit , please subscribe to this PR and as it is merged , please copy new projects to test-configs repository

**Comment by mahfouz72** [comment]
@nrmancuso tested in https://github.com/checkstyle/checkstyle/pull/15546

https://github.com/checkstyle/checkstyle/actions/runs/10516174001

**Review by nrmancuso — APPROVED** [review]

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit , please subscribe to this PR and as it is merged , please copy new projects to test-configs repository

Should I just copy-paste this into our list-of-project.properties because upon comparing i see other changes too apart from openjdk21.

**Comment by romani** [comment]
Yes, just copy paste

**Review by rnveach — APPROVED** [review]

**Pull request merged**
