### PR TITLE
minor: fixed checkstyle violations in releasenotes-builder

### PR DESCRIPTION
**Pull request by rnveach**

### CODE REVIEW

**Comment by romani** [comment]
CI is green in master. Where is a problem in CI ? how you detected it ?

**Comment by rnveach** [comment]
POM doesn't have maven-checkstyle in it, so nothing is running checkstyle on this code.
I found errors by running checkstyle manually through Eclipse with checkstyle project in same workspace.

**Comment by romani** [comment]
hmm, smth strange, here is checkstyle:
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/config/checkstyle.properties
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/pom.xml#L135

**Comment by rnveach** [comment]
it runs in travis but doesn't say anything
https://travis-ci.org/checkstyle/contribution/jobs/363119227#L550-L553

`propertiesLocation` and `sourceDirectories` is also missing from the POM.

**Comment by rnveach** [comment]
fixing in https://github.com/checkstyle/contribution/pull/294

**Pull request closed without merging**
