### PR TITLE
Issue #574: releasenotes-builder: fail execution if multiple labels

### LINKED ISSUE #574: releasenotes-builder: fail execution if multiple labels (that define category) are applied
Detected at https://github.com/checkstyle/checkstyle/issues/10842
Only one of "Bug", "Miscellaneous", "New Feature", "Breaking Compatibility" should be set of issue.

Better to fail build if uncertain situation happens.

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Fixes #574

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
Without Update:

Works on: Rahulkhinchi03/checkstyle-multiple-label
                 checkstyle/checkstyle

With update:

Works on: Rahulkhinchi03/checkstyle-multiple-label
 Not working with: checkstyle/checkstyle

Error:
svd

**Comment by romani** [comment]
Git history is ok now.

So on your local revert all your changes and apply them one by one to see where is a problem. Show here screenshot in debug mode right before exception

**Comment by Rahulkhinchi03** [comment]
@romani Just found out that it is working without making ` result = buildResultWithLabel(..)`

**Comment by romani** [comment]
Keep digging

**Comment by Rahulkhinchi03** [comment]
With the latest Code:
sfdgbfg

**Comment by Rahulkhinchi03** [comment]
Execution of releasenotes-gen.sh with latest changes.

```
rahul@rk7:~/Desktop/opensource/checkstyle$ ./.ci/releasenotes-gen.sh
PULL_REQUEST:
Cloning into 'contribution'...
remote: Enumerating objects: 7786, done.
remote: Counting objects: 100% (1060/1060), done.
remote: Compressing objects: 100% (462/462), done.
remote: Total 7786 (delta 537), reused 947 (delta 493), pack-reused 6726
Receiving objects: 100% (7786/7786), 2.84 MiB | 2.14 MiB/s, done.
Resolving deltas: 100% (3995/3995), done.
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.github.checkstyle:releasenotes-builder >-------------
[INFO] Building releasenotes-builder 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ releasenotes-builder ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ releasenotes-builder ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ releasenotes-builder ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/classes
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java uses or overrides a deprecated API.
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ releasenotes-builder ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ releasenotes-builder ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/classes
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java uses or overrides a deprecated API.
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ releasenotes-builder ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 16 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ releasenotes-builder ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/test-classes
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java uses or overrides a deprecated API.
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ releasenotes-builder ---
[INFO] Surefire report directory: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.checkstyle.templates.TemplateProcessorTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.767 sec
Running com.github.checkstyle.github.CommitMessageTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec

Results :

Tests run: 25, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ releasenotes-builder ---
[INFO] Building jar: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/releasenotes-builder-1.0.jar
[INFO] 
[INFO] --- maven-shade-plugin:2.4.2:shade (default) @ releasenotes-builder ---
[INFO] Including org.kohsuke:github-api:jar:1.99 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.9 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.13 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.6 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.12.6.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.12.6 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.12.6 in the shaded jar.
[INFO] Including org.eclipse.jgit:org.eclipse.jgit:jar:5.4.2.201908231537-r in the shaded jar.
[INFO] Including com.jcraft:jsch:jar:0.1.55 in the shaded jar.
[INFO] Including com.jcraft:jzlib:jar:1.1.1 in the shaded jar.
[INFO] Including com.googlecode.javaewah:JavaEWAH:jar:1.1.6 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.2 in the shaded jar.
[INFO] Including org.bouncycastle:bcpg-jdk15on:jar:1.61 in the shaded jar.
[INFO] Including org.bouncycastle:bcprov-jdk15on:jar:1.61 in the shaded jar.
[INFO] Including org.bouncycastle:bcpkix-jdk15on:jar:1.61 in the shaded jar.
[INFO] Including org.slf4j:slf4j-simple:jar:1.7.12 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:30.1.1-jre in the shaded jar.
[INFO] Including com.google.guava:failureaccess:jar:1.0.1 in the shaded jar.
[INFO] Including com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:3.0.2 in the shaded jar.
[INFO] Including org.checkerframework:checker-qual:jar:3.8.0 in the shaded jar.
[INFO] Including com.google.errorprone:error_prone_annotations:jar:2.5.1 in the shaded jar.
[INFO] Including com.google.j2objc:j2objc-annotations:jar:1.3 in the shaded jar.
[INFO] Including org.freemarker:freemarker:jar:2.3.29 in the shaded jar.
[INFO] Including commons-cli:commons-cli:jar:1.4 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including org.twitter4j:twitter4j-core:jar:4.0.7 in the shaded jar.
[INFO] Including javax.mail:mail:jar:1.5.0-b01 in the shaded jar.
[INFO] Including javax.activation:activation:jar:1.1 in the shaded jar.
[WARNING] bcprov-jdk15on-1.61.jar, jackson-annotations-2.12.6.jar, bcpg-jdk15on-1.61.jar, jackson-databind-2.12.6.1.jar, jackson-core-2.12.6.jar, bcpkix-jdk15on-1.61.jar define 1 overlapping classes: 
[WARNING]   - module-info
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Attaching shaded artifact.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.040 s
[INFO] Finished at: 2022-07-27T23:56:08+05:30
[INFO] ------------------------------------------------------------------------
Cloning into 'checkstyle'...
remote: Enumerating objects: 208196, done.
remote: Counting objects: 100% (270/270), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 208196 (delta 147), reused 180 (delta 102), pack-reused 207926
Receiving objects: 100% (208196/208196), 81.91 MiB | 3.43 MiB/s, done.
Resolving deltas: 100% (119368/119368), done.
LATEST_RELEASE_TAG=checkstyle-10.3.1
CS_RELEASE_VERSION=10.4

[WARN] Issue #11637 "Use Shellcheck to resolve violations code in Shell Script" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11637
[WARN] Issue #11719 "Pitest: Activate "ALL" mutator group" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11719
[WARN] Issue #6658 "pitest: increase mutation coverage for pitest-imports profile to 100% " is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/6658
[WARN] Issue #11720 "Pitest: Kill all surviving mutations" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11720
[WARN] Issue #11140 "Solve fb-contrib errors" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11140
[WARN] Issue #11277 "update code base to have javadoc tag to explain noinspection tag content" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11277
[WARN] Issue #11163 "Enforce file size on Java inputs" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11163
[WARN] Issue #6207 "Expand XPath IT Regression Testing" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/6207
[WARN] Issue #11446 "Update Tests to use new 'verifyXxxxxx' method or 'execute' that use inlined config in Input files" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11446
[WARN] Issue #11214 "Specify violation messages in input files." is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11214

[ERROR] Issue #7576 have more than one release label! Please set only one label from breaking compatibility, bug, miscellaneous, new feature, new module at https://github.com/checkstyle/checkstyle/issues/7576

Generation ends with 1 errors.
rahul@rk7:~/Desktop/opensource/checkstyle$ 


```

**Comment by romani** [comment]
You moving code out to method damaged logic, revert this refactoring and test. 
At the end make refactoring in such way to not damage logic.

**Review by romani — APPROVED** [review]
ok to merge, I tested this on local, works good, I saw error and content of release notes is same after fixing issue lablel

**Pull request merged**
