### PR TITLE
config: uncomment many projects in projects-to-test-on.properties

### PR DESCRIPTION
**Pull request by strkkk**
Useful for https://github.com/checkstyle/checkstyle/pull/9258

Left commented out
1. Duplicated projects with exclusion (default project list does not need duplication)
2. Open jdk repos (very heavy, can take a lot of time to create report for them)

### CODE REVIEW

**Comment by rnveach** [comment]
Are we sure no other existing checkstyle CI is using this file and uncommenting things manually?

**Comment by romani** [comment]
Looks like we do not use it https://github.com/checkstyle/checkstyle/search?q=projects-to-test-on.properties&type=

**Review by romani — APPROVED** [review]
I think we can remove duplicates with excludes, it was used when we had no diff.groovy.

Old jdk can be removed, and keep only jdk9.
We can activate it a bit later, as we see benefits of new model of regression testing.
Or we can activate not and contributors can be advised to make copy of this file he is not lucky. But majority of executions will be lucky.

**Comment by strkkk** [comment]
I removed project with exclusions, also openjdk is changed to git repo because github action does not support mercurial

**Comment by nmancus1** [comment]
> Are we sure no other existing checkstyle CI is using this file and uncommenting things manually?

There is:

```bash
➜  checkstyle git:(master) grep -R "projects-to-test-on.properties" | grep -v "groovy"
.ci/no-exception-test.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/no-exception-test.sh:  sed -i.'' 's/#guava|/guava|/' projects-to-test-on.properties
.ci/no-exception-test.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/no-exception-test.sh:  sed -i.'' 's/#guava|/guava|/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#hibernate-orm/hibernate-orm/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#spotbugs/spotbugs/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#spoon/spoon/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#spring-framework/spring-framework/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#Hbase/Hbase/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#pmd/pmd/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#elasticsearch/elasticsearch/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#lombok-ast/lombok-ast/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#RxJava/RxJava/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#java-design-patterns/java-design-patterns/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#MaterialDesignLibrary/MaterialDesignLibrary/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#apache-ant/apache-ant/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#apache-jsecurity/apache-jsecurity/' projects-to-test-on.properties
.ci/wercker.sh:  sed -i.'' 's/#android-launcher/android-launcher/' projects-to-test-on.properties
.ci/shippable.sh:  sed -i.'' 's/^guava/#guava/' projects-to-test-on.properties
.ci/shippable.sh:  sed -i.'' 's/#spring-framework/spring-framework/' projects-to-test-on.properties
.ci/shippable.sh:  sed -i.'' 's/#nbia-dcm4che-tools/nbia-dcm4che-tools/' projects-to-test-on.properties
.ci/shippable.sh:  sed -i.'' 's/#spotbugs/spotbugs/' projects-to-test-on.properties
.ci/shippable.sh:  sed -i.'' 's/#pmd/pmd/' projects-to-test-on.properties
.ci/shippable.sh:  sed -i.'' 's/#apache-ant/apache-ant/' projects-to-test-on.properties


```

**Comment by romani** [comment]
it looks like it is better to create new file that will be specific for github actions. Set of projects in it will be defined by limitation of github-action environment.

**Comment by rnveach** [comment]
@romani 
> it looks like it is better to create new file ...

Since everything is being merged into `diff.groovy` ( #531 ), does it make more sense to implement a feature in `diff.groovy` that will either:

1) Exclude all repos except the repos passed in by name.
2) Uncomment repos passed in by the name.

This way we can merge everything into 1 file and have functionality to run only the projects necessary?

I am preferring option 1 because we always tell everyone to run **ALL** repos and we only really start to exclude them in CI runs because of timeframe and specific error reporting.

**Comment by strkkk** [comment]
It seems to me that #531 is not close to be completed. 
For now github action takes only guava by default, which is not good.

@rnveach why you do not like separate file for github action?

**Comment by rnveach** [comment]
If we have no other choice it is fine, but I am just looking at the big picture and trying not to duplicate files for every single unique purpose. We will have to keep remembering to update each one and it won't be obvious to everyone, and eventually we'll forget one.

I am not saying this has to come before or after #531 , I was just using it as an example of consolidating and expanding regression.

**Comment by nmancus1** [comment]
> We will have to keep remembering to update each one and it won't be obvious to everyone, and eventually we'll forget one.

This was my thoughts as well; what if we "compromise" and create a CI task that verifies that both files are the same except for `#`'s?

**Comment by romani** [comment]
>does it make more sense to implement a feature in diff.groovy that will either:

This is tool, it simply should follow config file provided from outside and stricktly follow it.

**Review by romani — CHANGES_REQUESTED** [review]
lets use separate file for now to proceed quicker and avoid dependencies to other CIs

**Comment by strkkk** [comment]
@romani done

**Review by romani — APPROVED** [review]
ok to merge

**Review by pbludov — APPROVED** [review]

**Pull request merged**
