### PR TITLE
Issue #13045: update node version

### PR DESCRIPTION
**Pull request by AayushSaini101**
Related: https://github.com/checkstyle/checkstyle/issues/13045

### CODE REVIEW

**Comment by romani** [comment]
I lost a reason why we have this action, 
Maybe we can just remove it?

@nrmancuso , do you remember?

**Comment by nrmancuso** [comment]
I thought it was used to make comment in PR in diff report and site action, this is where I noticed it

**Comment by romani** [comment]
Please fix CI failure

**Comment by romani** [comment]
checkstyle-tester/README_MANUAL_EXECUTION.md:14: ]8;;https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md055---table-row-doesn-t-begin-end-with-pipes\MD055]8;;\ Table row doesn't begin/end with pipes
checkstyle-tester/README_MANUAL_EXECUTION.md:15: ]8;;https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md057---table-has-missing-or-invalid-header-separation-second-row-\MD057]8;;\ Table has missing or invalid header separation (second row)

Sounds like unrelated problems

**Review by romani — APPROVED** [review]
I do not know how to test it, let merge it and test in live, we can always revert if something is broken

**Comment by romani** [comment]
It works https://github.com/checkstyle/checkstyle/actions/runs/6424851753

**Pull request merged**
