### PR TITLE
Issue #614: Suppress all Idea Inspection violations

### PR DESCRIPTION
**Pull request by nrmancuso**
https://github.com/checkstyle/contribution/issues/614

There were some violations that would have taken more effort to add suppression for, so I just fixed them.

### CODE REVIEW

**Review by zayidmohamedy — COMMENTED** [review]
.

**Review by zayidmohamedy — COMMENTED** [review]
.

**Comment by nick-mancuso** [comment]
@Vyom-Yadav can you take over this PR and get it across the finish line?

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav can you take over this PR and get it across the finish line?

Sure, on it.

**Comment by nick-mancuso** [comment]
Using this PR to test out TC settings, I have changed the following in PR config only:
1. branch trigger to `+:*/head`
2. used last version of idea inspections

**Comment by nrmancuso** [comment]
Closed via https://github.com/checkstyle/contribution/pull/646

**Pull request closed without merging**
