### PR TITLE
add patch-diff-report-tool

### PR DESCRIPTION
**Pull request by attatrol**
This is initial implementation of patch-diff-report-tool, it creates difference report from 2 different checkstyle-result.xml files. It satisfies  <a title="Checkstyle XML Diff reports tool " href="https://github.com/checkstyle/contribution/issues/50" class="issue-link js-issue-link" data-id="124509767" data-error-text="Failed to load issue title" data-permission-text="Issue title is private">checkstyle/contribution#50</a>.
Here is <a href="http://attatrol.github.io/diff_tool_example/site.html">an example of the report.</a>

The issues:
1. it still uses modified maven style;
2. generation of xdocs and xrefs is a huge issue, i'll spend next couple of days solving it, happy to get any advice here, i want to know which tool did this for checkstyle site previously.
3. assuming xdoc generation won't be memory consuming, please test it on the same sets of data which caused OOME for ahsm.

### CODE REVIEW

**Comment by romani** [comment]
Usually in contribution i do not do code review to enforce good code. But if author is agree and ok to pass codereview we could make it enforced for now and for any other PR to this project. What is your choice ?

**Comment by attatrol** [comment]
@romani,
I'm intrested in review.

**Comment by attatrol** [comment]
maven-jxr is used for generating cross reference HTMLs and help added. 
Here is <a href="http://attatrol.github.io/diff_tool_example/site.html">an updated example of the report.</a></p>
It works quite good on linux, windows users may have incorrect paths to the XREFs and encoding issues.

**Comment by attatrol** [comment]
@romani 
I did some cleanup and now think the tool satisfies every requirement from the issue but having checkstyle own style. I don't know CSS quite well and have no designer skill to produce anything viable, so i still use slightly modified maven style and guess it is ok for internal debug utility.

Also i failed to understand why you run checkstyle-tester on travis for this tool. It doesn't need sites generated by it anymore, all it needs is 2 checkstyle-result.xml files and subject sources to run properly.

**Comment by attatrol** [comment]
@romani 
I did some cleanup and now think the tool satisfies every requirement from the issue but having checkstyle own style. I don't know CSS quite well and have no designer skill to produce anything viable, so i still use slightly modified maven style and guess it is ok for internal debug utility.

Also i failed to understand why you run checkstyle-tester on travis for this tool. It doesn't need sites generated by it anymore, all it needs is 2 checkstyle-result.xml files and subject sources to run properly.

**Comment by romani** [comment]
>  I don't know CSS quite well and have no designer skill to produce anything viable, so i still use slightly modified maven style and guess it is ok for internal debug utility.

yes, the simpler the better.

> Also i failed to understand why you run checkstyle-tester on travis for this tool. It doesn't need sites generated by it anymore, all it needs is 2 checkstyle-result.xml files and subject sources to run properly.

please point me to exact line where you see a problem. I do not understand you.
We do not use https://github.com/attatrol/ahsm in our CI at all for now, patch-diff-report-tool is not used also.

-------------------

I am merging this PR to make it initial to let other contributors already.
We will continue code review discussion in issue #50

**Pull request merged**
