### PR TITLE
Issue #14448: Migrate IDEA to highest true-scopes release v2022.3.3

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Aims to close https://github.com/checkstyle/checkstyle/issues/14448

Follow-up of https://github.com/checkstyle/checkstyle/pull/14604 and #837 

Based on observations from https://github.com/checkstyle/checkstyle/pull/14604#discussion_r1530584190 and further discussions.

last time we upgraded `2022.2.2` -> `2023.3.4`  at
https://github.com/checkstyle/contribution/commit/80a61391a97ac64f48d1ebef333c2910cd85b795 , but latest is problematic with scopes.

The latest IDEA release that we have used for update (2023.3.4) had issues with scopes.
A bit of research on different versions landed me on `v2022.3.3` being stable and good with scopes.

Link to PR in Checkstyle main repo with updated docker image : https://github.com/checkstyle/checkstyle/pull/14696

Link to docker image (personal) for testing update : 
https://hub.docker.com/layers/manishkk07/manish-k-07-checkstyle/jdk11-idea2022.3.3/images/sha256-3a659714655f8e033e648d894ac20eb110a0aa557f0f19821366cb54e4089305?context=repo

To pull image : `docker pull manishkk07/manish-k-07-checkstyle:jdk11-idea2022.3.3`

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
@romani ,
Lets try stable release `v2023.1.2` and hope it solves our issue with yaml violation in inspections 🤞🏻 
Better if we get this over with before gsoc period.. I haven't focused on drafting a proper proposal yet :)

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/pull/14696#issuecomment-2009554605

Looks like it is not working.

**Comment by MANISH-K-07** [comment]
image

@romani , I see that the image is building ?

> https://github.com/checkstyle/checkstyle/pull/14696#issuecomment-2009554605 Looks like it is not working.

I meant we had a bit more violations to suppress than the latest release that we previously worked on..
There were violations with v2023.3.4 too. @nrmancuso suggested that they all be suppressed by `@noinspection` javadoc tag
as mentioned at https://github.com/checkstyle/checkstyle/pull/14604#issuecomment-1976823540 and https://github.com/checkstyle/checkstyle/pull/14604#issuecomment-1984153844

**Comment by MANISH-K-07** [comment]
@romani , ping please

**Comment by MANISH-K-07** [comment]
@romani , ping please

**Review by romani — APPROVED** [review]
ok to merge

**Review by nrmancuso — CHANGES_REQUESTED** [review]
How do we know that we won't run into more issues with this version without having addressed all inspections?

**Comment by MANISH-K-07** [comment]
> How do we know that we won't run into more issues with this version without having addressed all inspections?

@nrmancuso , the problem with the latest version used in previous commit was that the scopes were messed up.
With `v2023.1.2`, the scopes were working fine, so we can proceed with limiting inspections scope from our generated files.
This should suppress all inspections violations except one.

 following `ClassEscapesItsScope` survives with the javadoc annotation. We will need to disable this and work on it separately

```
<problem>
<file>file://$PROJECT_DIR$/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java</file>
<line>256</line>
<module>checkstyle</module>
<package>com.puppycrawl.tools.checkstyle.checks.imports</package>
<entry_point TYPE="method" FQNAME="com.puppycrawl.tools.checkstyle.checks.imports.ImportControlLoader com.puppycrawl.tools.checkstyle.checks.imports.PkgImportControl load(java.net.URI uri)"/>
<problem_class id="ClassEscapesItsScope" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Class is exposed outside of its visibility scope</problem_class>
<description>Class <code>PkgImportControl</code> is exposed outside its defined visibility scope #loc</description>
<highlighted_element>PkgImportControl</highlighted_element>
<language>JAVA</language>
<offset>18</offset>
<length>16</length>
</problem>
</problems>
```

Please tell me if I am missing something else here?

**Comment by nrmancuso** [comment]
https://github.com/checkstyle/checkstyle/pull/14696/files has only an updated image with failing CI. 

>How do we know that we won't run into more issues with this version without having addressed all inspections?

Reply at https://github.com/checkstyle/contribution/pull/846#issuecomment-2025590700 does not answer this question.

**Comment by nrmancuso** [comment]
I am placing a blocked label on this until we work out which version we need to use.

**Comment by MANISH-K-07** [comment]
@romani , @nrmancuso , `2022.3.3` is a stable release.. highest of 2022 tag

CI at https://github.com/checkstyle/checkstyle/pull/14696 are green now.

The PR has been updated for description, commit msg and suppressions resulting with new image.
Please air the image to complete migration :)

**Review by romani — APPROVED** [review]
Ok to merge, small step but good step.

**Review by nrmancuso — APPROVED** [review]

**Comment by romani** [comment]
@MANISH-K-07 , please report to jetbrains a version where scope becomes broken, it will help them

**Pull request merged**
