### PR TITLE
Issue #456: update PMD repo in prop files

### PR DESCRIPTION
**Pull request by nmancus1**

### CODE REVIEW

**Comment by rnveach** [comment]
@romani @nmancus1 Was this PR tested in some type of regression or something else?

I am seeing a failure in a checkstyle PR related to PMD.
https://github.com/checkstyle/checkstyle/pull/7792#issuecomment-596604031
https://app.wercker.com/checkstyle/checkstyle/runs/build/5e669e477b63df001aea4819?step=5e669e74ee64ed0008fc5bf7

> NoExceptiontest - pmd elasticsearch lombok-ast
> 
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /pipeline/source/.ci-temp/contribution/checkstyle-tester/src/main/java/pmd/pmd-core/src/test/resources/net/sourceforge/pmd/cpd/files/file_with_utf8_bom.java
> Caused by: antlr.TokenStreamRecognitionException: Unexpected character 0xfeff in identifier

**Comment by rnveach** [comment]
The file in question has been around since January 2016. https://github.com/pmd/pmd/commits/master/pmd-core/src/test/resources/net/sourceforge/pmd/cpd/files/file_with_utf8_bom.java

The release right before this was 5.3.7 . https://github.com/pmd/pmd/releases?after=pmd_releases%2F5.3.8

I believe that is the latest we can move PMD version to.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L360
Wercker runs launch.groovy which can ignore files.

@nmancus1 Please confirm the issue is related to this PR locally. Once confirmed with console output, please add this file to ignore list and confirm running wercker command with changes will fix regression.

**Comment by nmancus1** [comment]
@rnveach Ok, I just restored the branch and I'm checking it out.

**Comment by rnveach** [comment]
> What should I use for Checkstyle config file? 

Look at https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L360 . You need to confirm the issue is this PR. Run the commands without your change, if it passes, add in your change and it should fail.
Once it is confirmed, we need a new PR updating the property files to ignore the problematic file and verify there are no more issues.

**Comment by nmancus1** [comment]
With change(ver 6.21.0): `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Error during page generation: Error rendering Maven report: Failed during checkstyle configuration: Exception was thrown while processing /home/nick/IdeaProjects/checkstyle/.ci-temp/contribution/checkstyle-tester/src/main/java/pmd/pmd-core/src/test/resources/net/sourceforge/pmd/cpd/files/file_with_utf8_bom.java`

With change(ver 5.3.7): `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Error during page generation: Error rendering Maven report: Failed during checkstyle configuration: Exception was thrown while processing /home/nick/IdeaProjects/checkstyle/.ci-temp/contribution/checkstyle-tester/src/main/java/pmd/pmd-core/src/test/resources/net/sourceforge/pmd/cpd/files/file_with_utf8_bom.java`

Without change(ver 5.3.0):`[INFO] BUILD SUCCESS`

**Pull request merged**
