### PR TITLE
Issue #332: Include EnumTrailingCommaAndSemicolonCheck

### LINKED ISSUE #332: Include EnumTrailingCommaAndSemicolonCheck
As [discussed](https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/709#issuecomment-409144962) in sevntu-checkstyle/sevntu.checkstyle#709, all sevntu checks should be used in the "contribution" project.

### PR DESCRIPTION
**Pull request by kariem**
Discussed in sevntu-checkstyle/sevntu.checkstyle#709

Resolves #332

### CODE REVIEW

**Comment by rnveach** [comment]
IDEA failure can be ignored. @romani Please review.

**Comment by kariem** [comment]
Renamed check based on this comment https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/709#discussion_r217457173

Last change reflects that change

**Comment by romani** [comment]
Check is not merged yet  - https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/722

**Comment by romani** [comment]
closing this PR as work on Check is not completed.

**Pull request closed without merging**
