### PR TITLE
Issue #17: Update windows CI to have run of groovy test tools

### PR DESCRIPTION
**Pull request by MEZk**
#177 

generateDiffReport and generateCheckstyleReport now receive too many parameters. Parameters should be represented as an objects of the specific class or the methods need to be refactored so as not to have so many parameters. Created an issue https://github.com/checkstyle/contribution/issues/182

### CODE REVIEW

**Comment by MEZk** [comment]
Stragne Exception in build log:

```
Running 'mvn clean' on src/main/java ...
Caught: java.io.IOException: Cannot run program "mvn" (in directory "C:\projects\contribution\checkstyle-tester"): CreateProcess error=2, The system cannot find the file specified
java.io.IOException: Cannot run program "mvn" (in directory "C:\projects\contribution\checkstyle-tester"): CreateProcess error=2, The system cannot find the file specified
	at launch.executeCmd(launch.groovy:284)
	at launch.executeCmd(launch.groovy:283)
	at launch$executeCmd$4.callCurrent(Unknown Source)
	at launch.runMavenExecution(launch.groovy:208)
	at launch$_generateCheckstyleReport_closure2.doCall(launch.groovy:80)
	at launch.generateCheckstyleReport(launch.groovy:63)
	at launch$generateCheckstyleReport$1.callCurrent(Unknown Source)
	at launch.run(launch.groovy:10)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	... 8 more
```

But directory ```C:\projects\contribution\checkstyle-tester``` exists as we can see from the log:

```
[delete] Deleting directory C:\projects\contribution\checkstyle-tester\src\main\java
[copy] Copying 1744 files to C:\projects\contribution\checkstyle-tester\src\main\java\guava
```

**Comment by rnveach** [comment]
@MEZk I think it is referring to `mvn` that it can't find, but I'm not sure why it would say that.
When I had issues with appveyor before, I just started running `dir` listings on everything to make sure everything was located where it should be.

**Comment by romani** [comment]
@MEZk ,

```
CreateProcess error=2, The system cannot find the file specified
java.io.IOException: Cannot run program "mvn" (in directory "C:\projects\contribution\checkstyle-tester"): CreateProcess error=2, The system cannot find the file specified
	at launch.executeCmd(launch.groovy:284)
	at launch.executeCmd(launch.groovy:283)
	at launch$executeCmd$4.callCurrent(Unknown Source)
	at launch.runMavenExecution(launch.groovy:208)
```

problem is not unlikely with "mvn", because "mvn --version" is printed fine. Something wrong with arguments for "mvn" in groovy - please extend logging and you will find a problem.

**Comment by MEZk** [comment]
@romani 
http://stackoverflow.com/questions/9674220/running-maven-from-java-code-in-windows

> 2. Use an absolute path to the mvn command.

**Comment by romani** [comment]
read log attentively - https://ci.appveyor.com/project/Checkstyle/contribution/build/275/job/vu6ug2q1gyhdwrhb#L30

**Comment by MEZk** [comment]
@romani 
I know that maven is installed. I cannot imagine why groovy's process executor cannot find M2_HOME.

**Comment by MEZk** [comment]
@romani @rnveach 
Cli commands on windows should be executed as ```cmd /c ... ```.
http://stackoverflow.com/questions/2701547/how-to-make-system-command-calls-in-java-groovy

I fixed the problem and created Windows test launchers for launch.groovy and diff.groovy.

**Pull request merged**
