### PR TITLE
minor: removes dead code in diff.groovy

### PR DESCRIPTION
**Pull request by rnveach**
Identified at https://github.com/checkstyle/contribution/pull/747#discussion_r1059680758 and moved off for quicker merge

### CODE REVIEW

**Comment by rnveach** [comment]
@nrmancuso ping
> ./.ci/travis.sh: line 119: mdl: command not found

and other failures.

**Comment by nrmancuso** [comment]
> @nrmancuso ping
> 
> > ./.ci/travis.sh: line 119: mdl: command not found
> 
> and other failures.

All is addressed in https://github.com/checkstyle/contribution/pull/746

**Comment by rnveach** [comment]
https://app.circleci.com/pipelines/github/checkstyle/contribution/21/workflows/88fb3974-c3d0-45f9-a103-78e63ab804d8/jobs/125
> Switched to a new branch 'patch-branch'
Caught: groovy.lang.MissingPropertyException: No such property: checkstyleToolBaseConfig for class: Config
groovy.lang.MissingPropertyException: No such property: checkstyleToolBaseConfig for class: Config

This is a real failure.

**Comment by rnveach** [comment]
Closing. The methods are actually used just not in their full form.

getDiffToolConfig:
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L40
getCheckstyleToolPatchConfig:
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L34
getCheckstyleToolBaseConfig:
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L31

I will need to look over these compared to my new changes

**Pull request closed without merging**
