### PR TITLE
Issue #243: Fix thymeleaf template to avoid incorrect placement of '\n'

### PR DESCRIPTION
**Pull request by MEZk**
issue #243 

Fixed thymeleaft template to have it formatted correct in case freemarker has problems. I'll switch the tool to freemarker in the next PR.

Template looks wired, but works.

### CODE REVIEW

**Comment by rnveach** [comment]
@MEZk Since this is a Java project and we can't see example of results with this change, maybe we should consider sometime adding a test that will print out a report for us like we do for patch-diff-report-tool and it's tests?

**Comment by MEZk** [comment]
@rnveach 
I opened the issue https://github.com/checkstyle/contribution/issues/245.

**Comment by MEZk** [comment]
No need in the new issue, I'll add UTs in the scope of this one.

**Comment by MEZk** [comment]
@rnveach 
Added UTs.

**Comment by rnveach** [comment]
@MEZk thanks.

**Comment by romani** [comment]
@MEZk , TC is not happy.

**Comment by MEZk** [comment]
@romani 
Fixed.

**Comment by MEZk** [comment]
@romani 
Please, check and merge this PR to let me reuse the test class and switch us to freemarker. Fix is ready.

**Comment by romani** [comment]
I am ok with change if it works.

**Pull request merged**
