### PR TITLE
checkstyle-tester: added apache apex project

### PR DESCRIPTION
**Pull request by rnveach**
Added apache apex to the list of projects to run regression on.

Added optional parameter to pom so could exclude files that can't be parsed by JXR, otherwise it throws an exception and stops the regression.
http://stackoverflow.com/questions/31207529/is-it-possible-to-pass-optional-parameter-testincludes-or-testexcludes-to-maven

Had to modify launch as this parameter can't be nothing, otherwise it will throw an exception too.

### CODE REVIEW

**Comment by romani** [comment]
> `if [ "$EXCLUDES" == "" ]; then`

I do not understand reason if this check. Such variable is used inside a loop that will have only last element of property file (one project). You use it for whole "mvn site" (multiple projects).

Please explain a reason of such update and how you are going to use it.

**Comment by rnveach** [comment]
Your right, I didn't realize where the loop was. It should be using `$EXCLUDES_ACCUM` but I'm not sure if that will work since pom says it is only a single exclude and `$EXCLUDES_ACCUM` is multiple.
Having this item in the pom was the only way to have JXR exclude files. I couldn't find any similar option that CS has.

**Comment by romani** [comment]
please state a problem first, after this I could think what we can do.

What you try to resolve ? (without details of how to resolve)

**Comment by rnveach** [comment]
Original issue is to skip certain Java files from JXR because:
````
contribution/checkstyle-tester$ mvn -e --batch-mode clean site -Dcheckstyle.excludes=**/src/main/resources/** -DMAVEN_OPTS=-Xmx3024m -X
.....
[DEBUG] parsing... apache-incubator-apex-core-c2008f2/apex-app-archetype/src/main/resources/archetype-resources/src/test/java/__packageInPathFormat__/ApplicationTest.java
.....
Caused by: java.lang.NullPointerException
    at org.apache.maven.jxr.pacman.JavaFileImpl.parse(JavaFileImpl.java:108)
    at org.apache.maven.jxr.pacman.JavaFileImpl.<init>(JavaFileImpl.java:64)
````

So we added exclude to pom and have it customizable. But then this issue showed up if and only if `$EXCLUDES_ACCUM` is empty (setting jxr-plugin.exclude to empty):
````
mvn -e --batch-mode clean site -Dcheckstyle.excludes= -Djxr-plugin.exclude=
.....
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.0:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.0:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.0:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.0:site failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.0:site failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.codehaus.plexus.util.AbstractScanner.normalizePattern(AbstractScanner.java:309)
	at org.codehaus.plexus.util.AbstractScanner.setExcludes(AbstractScanner.java:296)
	at org.apache.maven.jxr.pacman.PackageManager.parse(PackageManager.java:111)
	at org.apache.maven.jxr.pacman.PackageManager.process(PackageManager.java:161)
	at org.apache.maven.jxr.JXR.xref(JXR.java:262)
````

**Comment by romani** [comment]
> if [ "$EXCLUDES" == "" ]; then

so there should be EXCLUDES_ACCUM, am I right ?

**Comment by rnveach** [comment]
> so there should be EXCLUDES_ACCUM

Yes. But I haven't tested if that will work as the pom's definition is for a single exclude and EXCLUDES_ACCUM is multiple exclusions.

**Comment by rnveach** [comment]
@romani I tested this with multiple projects with multiple excludes and it did not work.
`mvn -e --batch-mode site -Dcheckstyle.excludes=,**/resources-noncompilable/**/*,,**/src/main/resources/** -Djxr-plugin.exclude=,**/resources-noncompilable/**/*,,**/src/main/resources/**`

I will go back and think on how to fix this for `launch.sh` as I'm not seeing a work around right now.
I was able to apply this to `launch_ahsm` (which I need to push an update for) as I only run the maven site command on each project separately, not as a whole, because of the amount of violations for indentation.

**Pull request closed without merging**
