### PR TITLE
Issue #355: support local projects VCS-independently

### LINKED ISSUE #355: local repos in checkstyle-tester
The documentation of checkstyle-tester suggests it once supported local paths for repos.
While this is still possible when it is a local Git or Hg repository (example gets fixed in #354), it would be nice to support a "local" type to support any VCS including none, local repositories with modified working trees and it would also save the space in `repositories`.

Actually what I suppose ist just this which I could PR if you like it:

```diff
-                cloneRepository(repoName, repoType, repoUrl, commitId, reposDir)
                 deleteDir(srcDir)
-                copyDir(getOsSpecificPath("$reposDir", "$repoName"), getOsSpecificPath("$srcDir", "$repoName"))
+                if (repoType == 'local') {
+                    copyDir(repoUrl, getOsSpecificPath("$srcDir", "$repoName"))
+                } else {
+                    cloneRepository(repoName, repoType, repoUrl, commitId, reposDir)
+                    copyDir(getOsSpecificPath("$reposDir", "$repoName"), getOsSpecificPath("$srcDir", "$repoName"))
+                }
```

### PR DESCRIPTION
**Pull request by Vampire**
Closes #355

### CODE REVIEW

**Comment by romani** [comment]
Ok to merge, @rnveach please review.

**Comment by rnveach** [comment]
I will review in more detail, one thing I noticed missing is documentation in the read me on how to use this new feature.

**Comment by Vampire** [comment]
Yes, I wanted to add this after your readme changes got merged, will add it later on. I didn't expect romani accepting it that fast. :-D

**Comment by Vampire** [comment]
Now you were too fast for me to add the docu.
Follup: #358

**Comment by romani** [comment]
>Now you were too fast for me

You, created so much issues,PR, questions ... You will keep me busy for a week or two for sure

**Comment by Vampire** [comment]
Sorry. :-D

**Pull request merged**
