### PR TITLE
Issue #614: resolves idea violations

### PR DESCRIPTION
**Pull request by rnveach**
Issue #614

This doesn't resolve all of them but it is a start.

### CODE REVIEW

**Comment by rnveach** [comment]
Violations left after this PR:

Abstraction issues
['public' method with 'boolean' parameter (Errors) (1)](https://teamcity.jetbrains.com/viewLog.html?buildId=4040648&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsPullRequest#)
Class metrics
[Overly complex anonymous class (Errors) (1)](https://teamcity.jetbrains.com/viewLog.html?buildId=4040648&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsPullRequest#)
Inheritance issues
[Abstract class without abstract methods (Errors) (2)](https://teamcity.jetbrains.com/viewLog.html?buildId=4040648&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsPullRequest#)
JUnit
[JUnit test method without any assertions (Errors) (1)](https://teamcity.jetbrains.com/viewLog.html?buildId=4040648&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsPullRequest#)
Probable bugs
[String concatenation as argument to 'format()' call (1)](https://teamcity.jetbrains.com/viewLog.html?buildId=4040648&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsPullRequest#)
Security
[Insecure random number generation (Errors) (1)](https://teamcity.jetbrains.com/viewLog.html?buildId=4040648&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsPullRequest#)

**Comment by romani** [comment]
CI is not happy.

**Comment by rnveach** [comment]
None of the failures are from my changes.

**Comment by romani** [comment]
I restarted all. Travis is ok, known system problem on their side.
appveyor is very strange ....

**Review by romani — APPROVED** [review]

**Pull request merged**
