### PR TITLE
Issue #73: Update an option and add examples of publication commands

### PR DESCRIPTION
**Pull request by Vladlis**
Issue #73

### CODE REVIEW

**Comment by romani** [comment]
@Vladlis , please rename authToken to githubAuthToken to make it clear what kind of token is required for builder.

**Comment by Vladlis** [comment]
@romani,
looks like the error from TC should be warning
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/config/intellij-idea-inspections.xml#L1743

**Comment by romani** [comment]
1) suppression of DesignForExtension is not a solution, @MEZk updated this Check not for ignoring. Please consult MEZk on how to fix.

2)
> looks like the errors from TC should be warnings

it is already a warning, but TC do not care about severity, all violations fail the build. To disable rule we use `... enabled="false" ...`.

Need to be resolved, as we use the same rule in main project too.

**Comment by romani** [comment]
CIs was red even before your PR.
Fixed.
@Vladlis , please rebase your changes on latest code. ALL CIs should be green , if not , it caused by your PR - please fix.

**Comment by Vladlis** [comment]
Rebased

**Pull request merged**
