### PR TITLE
Issue #453: add links to report headings in patch-diff-report

### PR DESCRIPTION
**Pull request by rnveach**
Issue #453

### CODE REVIEW

**Comment by rnveach** [comment]
Before: http://rveach.no-ip.org/checkstyle/regression/320/openjdk7/index.html
After: http://rveach.no-ip.org/checkstyle/regression/321/openjdk7/index.html#Configuration

The header color change is due to the CSS assigned to the links. I can change this if we want to keep the original red.

**Comment by rnveach** [comment]
http://rveach.no-ip.org/checkstyle/regression/321/pmd/index.html
Above is example with color fix and they are still links.

**Review by romani — APPROVED** [review]

**Comment by rnveach** [comment]
@romani Unless you want me to change, the current state of this PR is http://rveach.no-ip.org/checkstyle/regression/321/openjdk7/index.html#Configuration

**Comment by romani** [comment]
it woks good enough.
http://rveach.no-ip.org/checkstyle/regression/321/openjdk7/index.html#A1 still work, so it is good.

**Review by nrmancuso — APPROVED** [review]
I am conceptually OK with more links, link-ability is always good.

However, from https://github.com/checkstyle/contribution/issues/453:
>I would like to directly link to headings in the difference report like "Checkstyle configuration report" so I can specifically point to users and say their config is wrong.

In this case, it is probably better to point them to the actual config that is included in the regular diff report (linked xml file in index.html). 

Why don't the reports in this PR have the projects and config files links in index.html? http://rveach.no-ip.org/checkstyle/regression/320/index.html

Example of report with links: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/0633108_2022211127/reports/diff/index.html

**Comment by rnveach** [comment]
> it is probably better to point them to the actual config 

We did not have those configs at the time of the issue.

> Why don't the reports in this PR have the projects and config files links in index.html? 

My setup uses my scripts. https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/launch_diff.sh
This still runs patch-diff-report, so it is still the same result. It is just my scripts do other things that groovy doesn't like use Checkstyle CLI and allow for resume, pitest, and antlr.

**Pull request merged**
