### PR TITLE
config: add NoWhitespaceBeforeCaseDefaultColon

### PR DESCRIPTION
**Pull request by AkMo3**
PR for [Checkstyle #9728](https://github.com/checkstyle/checkstyle/pull/9728)

### CODE REVIEW

**Comment by rnveach** [comment]
@nick-mancuso Please run regression so we know we won't have negative consequences from merging this so late.

**Comment by rnveach** [comment]
Rebased PR on latest master.

**Comment by romani** [comment]
rebased

**Review by romani — APPROVED** [review]
Ok to merge
https://checkstyle.org/config_whitespace.html#NoWhitespaceBeforeCaseDefaultColon

**Pull request merged**
