### PR TITLE
minor: Update the readme file

### PR DESCRIPTION
**Pull request by Kevin222004**
minor: Update the readme file

### CODE REVIEW

**Comment by Kevin222004** [comment]
preview

**Comment by Kevin222004** [comment]
preview
image

**Comment by Kevin222004** [comment]
https://github.com/Kevin222004/contribution/blob/a28eb955e7435de8e6774088e6201d25536486b6/checkstyle-tester/README.md

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
@Kevin222004 , please fix CI
https://app.travis-ci.com/github/checkstyle/contribution/jobs/586434483#L342

**Comment by Kevin222004** [comment]
https://github.com/Kevin222004/contribution/blob/UpdateReadme/checkstyle-tester/README.md

**Pull request merged**
