### PR TITLE
Remove deprecated CodeNarc rules

### PR DESCRIPTION
**Pull request by friederbluemle**
Running the latest stable version of CodeNarc (`1.1`) with the StarterRuleSet file caused a couple of errors:

    ERROR: No such rule named [GrailsSessionReference]. . Expression: ruleClass. Values: ruleClass =     
    ERROR: No such rule named [AbcComplexity]. . Expression: ruleClass. Values: ruleClass = null

This PR removes the two deprecated rules, updates the test script with CodeNarc 1.1, and fixes several warnings in the `checkstyle-tester` Groovy scripts.

<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the branch of this pull request. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest target branch. If it isn't, or if you'd like me to combine something, please let me know, and I will make the necessary updates as soon as possible. Thank you!</sup></sub>

### CODE REVIEW

**Comment by romani** [comment]
Thanks a lot, but as mentioned of new codenarc version, please update it at https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/codenarc.sh#L3 to prove that it works

**Comment by friederbluemle** [comment]
@romani Thanks for the reply. Sure, let me update it.

**Comment by rnveach** [comment]
> File: diff.groovy
> CodeNarc completed: (p1=0; p2=11; p3=18) 10701ms
> CMD2=" && ./codenarc.sh . diff.groovy > diff.log && cat diff.log && grep '(p1=0; p2=10; p3=18)' diff.log"

It seems p2 went up by 1.
@friederbluemle To make CI pass, please update counts to new numbers.
Counts can be found at https://github.com/checkstyle/contribution/blob/master/.travis.yml#L64-L65 .

**Comment by romani** [comment]
> please update counts to new numbers.

Number should always go down. Please in separate commit apply some fixes to code to match previous Lev of quality or be better.

**Comment by rnveach** [comment]
> File: launch.groovy
> CodeNarc completed: (p1=0; p2=26; p3=6) 8724ms

**Comment by romani** [comment]
P2 going down, good.
Just update Travis config to match actual state

**Comment by friederbluemle** [comment]
It actually did go up (from 23 to 26 p2 warnings).

I added another commit to fix several warnings. Both file now have a lower count of p2 and p3 warnings. I updated .travis.yml accordingly. Thanks a lot for your help @romani @rnveach 👍

**Comment by romani** [comment]
@friederbluemle , just curious , how did you come up with desire to do such update ?

**Comment by friederbluemle** [comment]
Thanks for incorporating the changes. 👍

The reason for this PR was that I locally set up CodeNarc and needed a rules file. This repo came up first in a Google search, and using the most recent rules file from the `master` branch resulted in the errors that we just fixed.

The reason why I asked for a regular merge basically comes down to the rewriting of the commits (changing the committer ID and the commit hash) that happens when they are cherry-picked or squashed by GitHub. This in turn results in:

1. Me having to **force delete** my local branch (leaving with an uneasy feeling, not knowing if I'm not accidentally throwing away changes without manually/explicitly comparing the branch heads)
1. The removal of the commit signature - I sign all my commits with my GPG key, and by rewriting the commits this **signature is lost**

**Pull request merged**
